### ISSUE TITLE
Make plugins/extension develoment more "automatic"

### ISSUE THREAD

**Issue by Ashwolaa** [PyMoDAQ/PyMoDAQ#411]
Currently the developement of plugins, despite being well documented, is still quite tedious for new users and even for veterans sometimes.

To make this aspect more accessible, one can imagine a GUI or script with arguments/questions that would automatically:
- download the plugin template with the correct needed folders (instruments/extensions)
- fill the name entry in it to be consistent with pymodaq syntax and other relevant information in the pyproject.toml file
- do automatic testing on the behavior of the instrument/extension

**Comment by seb5g** [comment]
please look along the line of [coockie-cutter](https://github.com/cookiecutter/cookiecutter)

**Comment by Ashwolaa** [comment]
Since we use this Instrument entry, should we change the template to correctly represent the structure given in the toml file such as:
- app
- instruments
-- daq_move
-- daq_viewer
- extensions

**Comment by seb5g** [comment]
well could do but I think daq_move_plugins and daq_viewer_plugins makes it sufficiently explicit... and it would be a hassle to take care of the change for all old style plugins...

**Comment by Ashwolaa** [comment]
Hey everyone,

Here is a first draft of a plugin installer app with a demo. I decided to use gitpython as it feels more intuitive for me for now and it also well suited for git tools actions.

Currently:
- The user picks the git folder it is interested in, in practice, I am making a local copy in the temp directory to extract the structure in a dictionnary. I am thinking of storing it as an xml file in the config/log folder for example later on to avoid going through this step each time.

- The user fills the details, plugin name, author, ...
- The user press goes which launches a clone procedure and fills the relevant information in the toml files.
- The user can also install the cloned folder through a button that essentially does a pip install.

https://github.com/user-attachments/assets/c08eea70-70ea-4175-bd4f-92376a181a67

I am now thinking of now adding (big) buttons/actions to add the instruments/extensions of choices, if you have some preference on the icons, send them to me.

Obviously, I am open to comments/critics

**Comment by seb5g** [comment]
That looks already very good!

Some questions/thought:

* But then how do you install your application? You still need an environment, python installed and I guess this app that's a bit like the plugin manager? 
* By the way this could be kind of added to the plugin manager as a multi-tool interface. 
* I implemented on the 5.0.x branch of the template, the new schema using only pyproject.toml. could you have a look and tell me if it looks particularly difficult or not?
* It could be nice if your implementation with GUI could use some command line features. Like this depending the preference of a use they could either use the command line (like coockie cutter) or your GUI but with the same backend!

**Comment by quantumm** [comment]
Looks great! ;)

**Comment by Ashwolaa** [comment]
> * But then how do you install your application? You still need an environment, python installed and I guess this app that's a bit like the plugin manager?
> * By the way this could be kind of added to the plugin manager as a multi-tool interface.

yes, I fully agree. I had the same impression when starting the code that both should come as a single GUI. I started as a custom app. I will start looking in the plugin manager code to see how to connect both.

> * I implemented on the 5.0.x branch of the template, the new schema using only pyproject.toml. could you have a look and tell me if it looks particularly difficult or not?

I will check but I believe it currently works with both version 4 and 5

> * It could be nice if your implementation with GUI could use some command line features. Like this depending the preference of a use they could either use the command line (like coockie cutter) or your GUI but with the same backend!

I will look into it, I am more a fill the form / tick checkbox / press button type of guy but the old fashion way never dies I guess.

**Comment by seb5g** [comment]
> I will look into it, I am more a fill the form / tick checkbox / press button type of guy but the old fashion way never dies I guess.

who are you saying is old? :-)

actuallly many python/linux officionados only use command line... which is a bit more efficient that yougster clicking everywhere

**Comment by Ashwolaa** [comment]
> > I will look into it, I am more a fill the form / tick checkbox / press button type of guy but the old fashion way never dies I guess.
> 
> who are you saying is old? :-)
> 
> actuallly many python/linux officionados only use command line... which is a bit more efficient that yougster clicking everywhere

Haha sure I still have some good memories of my first arguments given in the command line, but switching between boxes with tab is as efficient and still offers the ability to see the whole layout.
Anyway, let's go for both!
