### ISSUE TITLE
[BUG] Problem upon installation of the Newport plugin

### ISSUE THREAD

**Issue by martinluttmann** [PyMoDAQ/PyMoDAQ#691]
### Describe the bug

Dear all,

I have been facing the following issue with the pymodaq-plugins-newport package. Installing this plugin (from the plugin manager or manually using "pip install") leads to a failure of pymodaq. In particular, entering the commands "dashboard", "daq_viewer" or "daq_move" in the terminal does not launch anything, so pymodaq is unusable. No error message is displayed and nothing gets written in the log file. This problem disappears upon uninstalling the newport plugin.
I am using pymodaq 5.0.18 right now with python 3.11.13, but the problem also occurs with other versions of pymodaq.
Could it be a problem with the new versions of pymodaq_utils and pymodaq_gui ? I currently have pymodaq_utils==0.0.19 and pymodaq_gui==5.0.22. Should I upgrade those ? And how ? 

Thank you in advance,

Martin

**Comment by seb5g** [comment]
This plugin was not up to date and was working only with pymodaq 4 . I just published two release targeting pymodaq 4 (4.0.0) and pymodaq 5 (5.0.0). Try the last one, on my computer the newport actuators appeared correctly

**Comment by martinluttmann** [comment]
Thank you Seb. I actually found this in the log file 


> WARNING - daq_move_Conex plugin couldn't be loaded due to some missing packages or errors: Could not load file or assembly 'ConexAGAPCmdLib' or one of its dependencies. The system cannot find the file specified.
> File name: 'ConexAGAPCmdLib'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
>    at Python.Runtime.AssemblyManager.LoadAssembly(AssemblyName name)
>    at Python.Runtime.CLRModule.AddReference(String name)

> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

I tried uninstalling/reinstalling the conex software without success.



 I also tried installing the version 5.0.0 of the newport plugin you mention, unfortunately the problem persists. However, I tried on another computer where noting is installed (in particular the conex software is not installed) and there pymodaq works! The newport plugins appear in the list of the available daq_moves...



 I am a bit lost, as this plugin had been working fine in our python environment so far. It is not the 1st time that this kind of things happen (a plugin that stops working for no reason): do you think that some stuff get updated automaticcaly without our consent, leading to conflicts ?

**Comment by seb5g** [comment]
when something weird happens, make sure to delete all the configuration files (in both .pymodaq folders) especially if you use multiple environment as there is only one config folder for all environment. 

As for the the conex lib this is a dll in dotnet that should be found on your system... The location is somehow hard coded in the plugin (should be in a confid file nowdays...) 👍 

<img width="1502" height="514" alt="Image" src="https://github.com/user-attachments/assets/d8510778-966f-418e-aeb8-8e2d854673cd" />

so check that this is the same for you. You can try to run those few lines in your python console within your env to debug it

**Comment by martinluttmann** [comment]
I deleted the config files in the .pymodaq folder that is in the user's folder, could you indicate where I can find the second folder ?

yes I saw that this file is hard coded, but it does not make sense that it leads to an infinite waiting time upon entering usual the pymodaq commands... whereas on a computer that does not have the required dll it works.

**Comment by seb5g** [comment]
On program data folder, see https://pymodaq.cnrs.fr/en/latest/user_folder/configuration.html#configuration
